---
# This is the policy for the web to database layer.

- name: Match Web Server to Database Tier
  ansible.builtin.set_fact:
    policy_creation_policy_match: true # Set the fact that we did match a policy
    policy_creation_source_address_group: PRESET_WEB_TO_DATABASE_SOURCE # In this case, the policy preset is an address_group type
    policy_creation_destination_address_group: PRESET_WEB_TO_DATABASE_DESTINATION # Destination addr group
    application_group: PRESET_WEB_TO_DATABASE # If an application is passed, we should also include it in the policy.
    policy_creation_device_group: Lab # Finally, we set the device group!
  when:
    - policy_creation_source_ip is defined
    - policy_creation_destination_ip is defined
    - "'10.10.199.0/24' | ansible.utils.network_in_network( policy_creation_source_ip )"
    - "'10.10.200.0/24' | ansible.utils.network_in_network( policy_creation_destination_ip )"
